### ISSUE TITLE
Empty thank you page after payment

### ISSUE THREAD

**Issue by rickalday** [graphpaperpress/Sell-Media#670]
Nothing but the page title shows up when the customer is redirected after a successful payment.

**Comment by chrisbemis** [comment]
I noticed this issue when I attempt to pay using a Paypal account with an email address that is registered to a different user. The sale goes to the user registered with the Paypal account. The user who purchased the media does not get the file download link.

**Comment by MichaelWeb** [comment]
@chrisbemis @bertbotha Is your SellMedia in "test" mode ? Are you using Paypal's sandbox account to make a purchase or is it a real transaction ?

**Comment by chrisbemis** [comment]
Sell media is in live mode. I tested this in PayPal and Stripe. What is happening for me is that the email address used for the PayPal or Stripe account is what determines who gets the order. 

In other words, if a customer has an account on my website with the same email address as their Stripe or PayPal accounts, the order goes through ok. 

If however, their PayPal or Stripe email addresses differ from their account email on my website, then a new customer account is created on my website with the PayPal or Stripe email address. The order goes to this new account instead of the account my customer previously created.

**Comment by thadallender** [comment]
Version 2.0 simplifies the PayPal integration steps. All you need to add is your email address on the Settings page. You don't have to save any special settings at PayPal anymore. These steps caused some confusion for users, so we streamlined things.

If your thanks page is empty or your payments still aren't showing up in Sell Media after payment at PayPal or Stripe, check these possible problems:

1. You don't have the required PHP cURL extension installed on your server. This is how PayPal/Stripe talk back to your website. Ask your web host to install if it's not installed.
2. You are incorrectly testing PayPal Sandbox. Both the Buyer and Seller accounts have to be PayPal Sandbox accounts. You cannot mix a REAL PayPal account with a TEST PayPal Sandbox account. It won't work.
3. Your web host has a firewall that is blocking incoming pings from PayPal or Stripe. We've seen this happen once before with European servers (Germany). They blocked all incoming pings (IPN notifications) that didn't have a User-Agent defined. PayPal uses IP ranges 66.211.. and 173.0.. and visit the IPN URL with NO User-Agent. Some web hosting companies have their servers set up to block incoming pings when the User-Agent is not explicitly set (as is the case with PayPal's IPN). In this case, you'll want to modify your .htaccess file to override user-agent blocking with these address ranges.
4. You have a server misconfiguration that is preventing PayPal from receiving the required status code 200. Check your PayPal IPN History to see what the status codes are to help troubleshoot.
