### ISSUE TITLE
Multiple free downloads (no-payment)

### ISSUE THREAD

**Issue by mvbaxter** [graphpaperpress/Sell-Media#689]
Just had a brief chat with Thad about using Sell-Media together with Stock Photography theme to create a free distribution center for media downloads within our intranet environment.  I would be happy to do the work, with a little guidance.  Here is what we need:

In addition to the layout features provided by the Stock Photography theme, we would like to provide all of our downloads to other departments for free.  Looking at the "Free Downloads" extension, it seems a bit clunky for a situation where ALL downloads are going to be free.  We DO need to track all downloads, but would prefer if each user/site member could download multiple files after "shopping" around.

We would consider just using a Download Manager/Counter, but we also want a "Lightbox" feature for our user base to be able to set-aside multiple photos/videos for consideration.

In a perfect world, each lightbox could be shared via URL to co-workers, etc.

Finally, we would love for the cart to skip any payment gateways whenever there is zero cost, because all of our media would be free.

I would love it if you could provide guidance to help me add those customized features, either as plugin options, or extensions to your plugin. I need something up and running within the next 2-4 weeks.

Thanks!

**Comment by samedgecombe** [comment]
hi mvbaxter. I have been working on a plugin for this. The way it works is creating a new user role "Trusted customer" (although this could be changed). Then all users with this role get to Download original size images directly and a record of the sale is made in the backend. I was thinking to add ability to add images to the lightbox and then download them, but it was easier just to download them 'on click'. All downloads still show up in the users Dashboard though. I haven't had a load of time to work on this due to work/family, but I create page for this on Github maybe.

**Comment by rickalday** [comment]
There's an extension for this now: https://graphpaperpress.com/plugins/sell-media-access-control/

**Comment by mvbaxter** [comment]
Very nicely done!  Thank you for this!
