### ISSUE TITLE
Magnifier off-centre

### ISSUE THREAD

**Issue by icenando** [graphpaperpress/Sell-Media#704]
Magnifier is far off-centre, causing most of the image to be out of its reach.

Magnified image seems to be anchored at the top left corner. The further you get from that corner, the further off the image is.
![screen shot 2015-05-14 at 18 47 09](https://cloud.githubusercontent.com/assets/12436042/7637982/ab0862f4-fa69-11e4-8c00-370c39aa8364.png)

**Comment by rickalday** [comment]
Known issue with the Magnifier and Watermark.

**Comment by TheShihan** [comment]
Why is this a "wontfix"? So there will never be a site with watermarks and magnifier working in combination?

**Comment by TheShihan** [comment]
Well I tried to get watermarking to work with the "Image Watermark" plugin you mentioned in another issue, disabled Sell Media Watermark first. Long story short is that it doesn't seem to be compatible with Sell Media and I guess it is because sell media copies away the original full size image to a different folder when you create a new product using the media. This results in a new copy of the image using the same dimensions of the "large" version, also the large version is being regenerated (using also "large" dimensions of course) and because the now (new) original image has the same dimension as the large dimension no watermark is being added. It only works as long as I upload an image beforehand and not use it in a sell media product.

![screen shot 2015-09-24 at 22 38 07](https://cloud.githubusercontent.com/assets/511436/10086259/ad331558-630d-11e5-938c-bcc9150f3039.png)
