### ISSUE TITLE
Keyword handling

### ISSUE THREAD

**Issue by MYSTERYouse** [graphpaperpress/Sell-Media#753]
Hello guys,
 
I looked trough the keyword handling during upload. Following scenario:

1. Upload image - fill in keywords on the upload tab
2. Check the upload and the keywords in Sell media items is not present

Questions

Q1: Do I understand this right that the keywords need to be assigned on a sell media item basis in order to have them shown on the front-end? I see that the keywords are present in the standard wordpress media library which means they are tied to the low-res images, which has no point for SM.

Q2:Would there be a way to access the sell media keyword list? For example upload or create the keywords that can be later used on the images?

The idea is that if you want to build up the library, the keyword are probably the most important keys that can navigate the user trough your portfolio (except search function which you can use once you know what you look for).

**Comment by thadallender** [comment]
Hey @MYSTERYouse,

Thanks for the feedback. Here is how keywords work in Sell Media:

1. If you add a gallery of images to a Sell Media entry, then keywords are imported and assigned to the image attachment.
2. If you add only one image to a Sell Media entry, then keywords are imported and assigned to the entry itself.

This distinction is important because:

Imagine if you shot an event, such as the Oscars, and you applied keywords to the images, and then uploaded all of the image to a single Sell Media entry (you created a gallery). You wouldn't want a search for "Tom Cruise" to pull up the Gallery containing all images from the Oscars. You would expect to just see images of Tom Cruise.

But because of this distinction, the search functionality in Sell Media becomes more complicated since we're technically dealing with 2 different post types: sell_media_item and attachment. In Sell Media 2.1.5, we default search to just sell_media_item keywords. Users were asking for this. We added a "Search Everything" option so users can search titles, content, captions, attachment keywords, etc.

Q1: When you say, "shown on the front-end," can you elaborate? Do you mean shown on search pages? If so, yes. That said, when you check "Search Everything" it searches attachment keywords also.

Q2: Yes. The link is hidden from the menu to minimize clutter. Just add this to your site url:

/wp-admin/edit-tags.php?taxonomy=keywords&post_type=sell_media_item

Do you think we should add Keyword link to the Sell Media admin menu?

**Comment by MYSTERYouse** [comment]
Thank you for explanation, definitely - relying on keyword search makes most sense if you are building up the photo library. I remember the threads where these ideas were discussed. 

It is up to the SMuser
A. whether he wants to show the visitor only images that can be purchased. If you are looking for internal long-tail search, you can use the search everything. But this makes only sense if the SMuser is creative and has lot's of data written in the titles, content, captions.
B. whether he is using the galleries (if yes, then you need to rely on the attachment keywords)

To the Q1 - the broader thinking behind my keyword obsession comes from SEO perspective and site architecture, where I would want to push my keyword archives http://yourweb.com/keywords/term/ as dominating pages instead of hiding them from search engines like I would probably do in case of keywords used for tagging the articles (or don't use them at all).

Let's say you are nature or landscape photographer, you will be photographing country with "rice fields", "old building", "sunset", "waterfall" etc. These kind of things are probably your most valuable descriptors of what you do. This way you can effectively reference your content in your blog posts and promote the dynamically expanding pages for a given keyword and build an awareness around the type of photography you provide. 

You cannot expect the user to search for a phrase on your page, unless you have a huge gallery of images for sale from a relatively known market. They will rather browse trough your past few galleries. Providing them with keyword based archives might help you to "educate" your visitor of what your work is really about. In this I would probably reference the keyword as a "theme"

Off topic: Another aspect that I am not yet clear about is the "thin content" which basically each page where you show individual image is. Time will tell once the catalog grows how it will be perceived by google.

I know this would fall more into the best practices for SM, but take it as a feedback and my thinking process behind this.

---

Somehow in my dev environment the keywords are not being imported at all. Not into attachment nor SM - could you check in your dev if it works for the attached file, github does not strip the ITPC, I checked.

keywords on file: atketika, bolest, deti, po behu, unava
metadata caption: MSR v atletike (this is pulled correctly for me)

![msr_girls](https://cloud.githubusercontent.com/assets/5697965/13633872/0519a0b8-e5f2-11e5-8d7e-f97ddfe47e77.jpg)

**Comment by MYSTERYouse** [comment]
I believe the scenario 2, you mentioned:

> If you add only one image to a Sell Media entry, then keywords are imported and assigned to the entry itself.

does not work or does not load the keywords from the attachment page of a given file.
