### ISSUE TITLE
Sell Media Search Form to Sell Media Filters

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#773]
I had a similar feature request that was closed, but I am not sure if the request was understood.

Sell Media has a search from:  the one used to display a search form exclusively for searching items for sale within Sell Media. The short code is:  [sell_media_searchform].

I would like to include that "exclusive to sell media" search form as part of the [sell_media_filters] shortcode. 

Like this:

![c841db88-1a08-11e6-81c9-ca26561ef79f](https://cloud.githubusercontent.com/assets/18253020/15750963/f44b1380-28ad-11e6-8fc7-5e3c44e721cb.png)

Is this possible for a future release?

**Comment by thadallender** [comment]
Thanks. I definitely understand the request. The problem is that including another search form inside the Filters shortcode would cause two distinct problems:

1. Many themes (like Stock Photography, Sell Photos, etc.) are designed with the search form in the header or sidebar. For example: http://demo.graphpaperpress.com/stock-photography/filters/ Putting the search form in the Filters shortcode would essentially cause two forms to be displayed and would produce invalid HTML (duplicate ID's).

2. The Search form redirects to a new page and uses "query parameters" to show the search results. It would not reload on the Filters page, like the other options do. This would cause some UX confusion for users.

It's not that we're opposed to the feature request, it's just that there are technical reasons for not including it. If we can find a way to make it work, we'll def. consider it in the future.

**Comment by AoxoA-Create** [comment]
Ok.  Thanks for clarifying.
