### ISSUE TITLE
Price Groups not Saving Correctly

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#778]
I tried to create a new price group for prints.  I entered three lines/sizes, etc... It only saved one line after clicking the "Save Price Group" button.

Here is a repeated attempt to add another price/size line:  https://youtu.be/Qly4oChBCzI

Screen Shots:

1) only saved one line:
![screen shot 2016-08-08 at 7 58 18 am](https://cloud.githubusercontent.com/assets/18253020/17484018/cc6c0264-5d4d-11e6-9bec-ba2f21b8ef2f.png)

2) tried to enter another line:
![screen shot 2016-08-08 at 7 58 58 am](https://cloud.githubusercontent.com/assets/18253020/17484028/ddc860f2-5d4d-11e6-9a2d-643555762a05.png)

3) Clicked save and the page refreshed and did not save line:
![screen shot 2016-08-08 at 7 59 16 am](https://cloud.githubusercontent.com/assets/18253020/17484043/eb3c587e-5d4d-11e6-9f9a-18226fbcd8a5.png)

Please help with this as soon as you can.  Thanks.

**Comment by thadallender** [comment]
Price Names must be unique. Please confirm that works.

**Comment by AoxoA-Create** [comment]
Yes that worked.  I don't believe it was a requirement before the last update.  Why the change?

**Comment by thadallender** [comment]
It's always been that way, if I recall. The feature relies on WordPress core functions related to taxonomy terms and term meta.

**Comment by AoxoA-Create** [comment]
Are you sure? Looking back, i see I used the same price names in the screen shot to this issue:  https://github.com/graphpaperpress/Sell-Media/issues/763

Not sure how I got that to work.....but that the way I'd prefer it.  I guess I'll just add the size in there to make it unique.

**Comment by thadallender** [comment]
Prior to WordPress 4.4, there was no internal support for the kind of complex taxonomy/term/meta relationships required to create the Price Group functionality in Sell Media. So, we wrote our own database models to handle it. It was a huge undertaking to bring taxonomy/term/meta functionality into WordPress, as you can see from this 7 year old ticket in core WordPress:

https://core.trac.wordpress.org/ticket/10142

When WordPress 4.4 was released, we migrated our internal price groups to use the new core functions. Because of the complex nature of taxonomy/term/meta, WordPress requires unique names for each price group. If we supported non-unique term (price) names before, it was a flaw.

Sorry if this requires a slight modification to your naming structure, but I can assure you that having unique price names is a best practice moving forward.

**Comment by AoxoA-Create** [comment]
10-4
