### ISSUE TITLE
Creator never saved

### ISSUE THREAD

**Issue by erikksson** [graphpaperpress/Sell-Media#812]
if a product is created or modiefied you may add a creator.
unfortunately, that choice is never saved.
open the product again and the choice is lost

**Comment by codearryaas** [comment]
This issue has been fixed and will be released in the new version.

**Comment by erikksson** [comment]
sometimes I wonder a bit, if this product is still maintained/developped/alive.
This is a considerable bug - and as such would be fixed in another product within days..... here nothing happens for months....not good for customers and users.
my advice/hope: either commit to the product or communicate, that it is no more activly maintained.

**Comment by thadallender** [comment]
This issue was fixed months ago. If it's not working for you, check that you have the most recent version. If not, respond to the issue and provide feedback on your original issue.

This plugin is very active, with lots of new commits and features, all of which you can track on GitHub:

https://github.com/graphpaperpress/Sell-Media/graphs/contributors
https://github.com/graphpaperpress/Sell-Media/commits/marketplace

The public WordPress.org repo was updated just 25 days ago.
